### ISSUE TITLE
Documentation and examples?

### ISSUE THREAD

**Issue by alexandrefierro** [ARPA-SIMC/bufr2netcdf#12]
Greetings:

Could you please provide a documentation file/README on how to install and use this tool (i.e., simple examples)? 

Thanks,

**Comment by dcesari** [comment]
Hello. The bufr2netcdf documentation is quite sparse at the moment. This is tool tailored to the [Cosmo/ICON](https://cosmo-model.org/) meteorological models and their data assimilation system. Bufr2netcdf is part of a software suite developed by ARPA-SIMC including [wreport](https://github.com/ARPA-SIMC/wreport) and [dballe](https://github.com/ARPA-SIMC/dballe).

Some information about how to build the packages or use them within a container can be found in the [smnd project](https://github.com/ARPA-SIMC/smnd), while the basic usage instructions for bufr2netcdf are in the [dballe wiki](https://github.com/ARPA-SIMC/dballe/wiki/CosmoNetcdfConversion).
