### ISSUE TITLE
Build errors on rocky8 and fedora40

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/bufr2netcdf#15]
On rocky8, there are some errors including `/usr/include/wreport/vartable.h`:

https://simc.arpae.it/moncic-ci/bufr2netcdf/202409180840/master/rocky8/build.log

On fedora 40, it seems that implicit declarations aren't welcomed:

https://simc.arpae.it/moncic-ci/bufr2netcdf/202409180840/master/fedora40/build.log

**Comment by spanezz** [comment]
I pushed a `meson` branch on bufr2netcdf that replaces autotools with meson, which was about time, and easier than to figure out how to update autotools to work with C++17.

I've fixed the remaining code issues, and now it seems to build also on rocky8 and fedora40.

If you can confirm, then feel free to merge it into `master`
