### ISSUE TITLE
New DWD bufr tables available

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/bufr2netcdf#9]
Version 1.1.7-8, WMO BUFR Table Version 34. Can we update just by replacing v2/mnem_??? ?
I sent the update package by e-mail.

**Comment by spanezz** [comment]
Besides changing the format, there might be a off-by-one shift in the file names: the v2 tables started from `mnem_000`, while the v3 tables start from `mnem_001`. I don't know yet if it's significant

**Comment by spanezz** [comment]
All tests pass with the new tables

**Comment by dcesari** [comment]
I have an update of the mnemonics tables from DWD, up to version 41, is it safe to add the files `mnem_035` up to `mnem_041` (v3 format) to the tables/ directory? (probably they are useless if we do not add the equivalent WMO tables to wreport, but it is just to keep the package up do date).

**Comment by spanezz** [comment]
The good news is, it's perfectly safe.

The bad news is, bufr2netcdf is currently always using `mnem_014`. See https://github.com/ARPA-SIMC/bufr2netcdf/blob/master/src/namer.cc#L123

The comment in the code points at the fact that it is unclear what table to use when the input gribs are using different table versions. I'll open a new issue to work out what bufr2netcdf should do, and then implement it properly

**Comment by dcesari** [comment]
I have added the tables in order not to forget
